FROM node:16-alpine as build

WORKDIR /app

ARG REACT_APP_API_URL='https://oscarshub.com/api/v1'
ARG REACT_APP_SITE_KEY=6LfC45slAAAAABkj6lBmLgMloYyHLp3S_QcCW9Xq

COPY ./package.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx
EXPOSE 3000
# COPY ./nginx/default.conf /etx/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

