version: '3'

services:
  api:
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    build: 
      context: ./client
      dockerfile: dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app

  nginx:
    restart: always
    depends_on:
      - api
      - client
    build: 
      context: ./nginx
      dockerfile: dockerfile
    ports:
      - 80:80