version: '3'

services:
  api:
    build:
      dockerfile: dockerfile.dev
      context: ./server

  client:
    build: 
      context: ./client
      dockerfile: dockerfile.dev

  nginx:
    restart: always
    depends_on:
      - api
      - client
    build: 
      context: ./nginx
      dockerfile: dockerfile.dev
    ports:
      - 8000:80