version: '3'

services:
  api:
    build:
      context: ./server
      dockerfile: dockerfile.dev  
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    build: 
      context: ./client
      dockerfile: dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app

  nginx:
    restart: always
    depends_on:
      - api
      - client
    build: 
      context: ./nginx
      dockerfile: dockerfile.dev
    ports:
      - 8000:80