version: '3'

services:
  api:
    build:
      context: ./server
      dockerfile: dockerfile.dev  

  client:
    build: 
      context: ./client
      dockerfile: dockerfile.dev

  # nasaproject:
  #   image: oscardel13/nasa-project
  #   ports:
  #     - 5000:8000

  nginx:
    restart: always
    depends_on:
      - api
      - client
      # - nasaproject
    build: 
      context: ./nginx
      dockerfile: dockerfile.dev
    ports:
      - 8000:80