name: Oscars Work CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    steps:
      - uses: actions/checkout@v3
      # Docker Login
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      # Build Client and run test
      - run: docker build -t oscardel13/react-test -f ./client/dockerfile.dev ./client
      - run: docker run -e CI=true oscardel13/react-test npm test
      # Build Server and run test
      # - run: docker build -t oscardel13/server-test -f ./server/dockerfile.dev ./server
      # - run: docker run -e CI=true oscardel13/react-test npm test

      # Build Production Images
      # - run: docker build -t oscardel13/multi-client-3-9 ./client
      # - run: docker build -t oscardel13/multi-nginx-3-9 ./nginx
      # - run: docker build -t oscardel13/multi-server-3-9 ./server
      # - run: docker build -t oscardel13/multi-worker-3-9 ./worker

      # Push Images to docker hub
      # - run: docker push oscardel13/multi-client-3-9 
      # - run: docker push oscardel13/multi-nginx-3-9 
      # - run: docker push oscardel13/multi-server-3-9 
      # - run: docker push oscardel13/multi-worker-3-9 
