name: Oscars Work CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     # Docker Login
  #     - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  #     # Build Client and run test
  #     - run: docker build -t oscardel13/react-test -f ./client/dockerfile.dev ./client
  #     - run: docker run -e CI=true oscardel13/react-test npm test
  #     # Build Server and run test
  #     # - run: docker build -t oscardel13/server-test -f ./server/dockerfile.dev ./server
  #     # - run: docker run -e CI=true oscardel13/react-test npm test

  #     # Build Production Images
  #     - run: docker build -t oscardel13/oscarshub-client ./client
  #     - run: docker build -t oscardel13/oscarshub-nginx ./nginx
  #     - run: docker build -t oscardel13/oscarshub-server ./server
  #     # - run: docker build -t oscardel13/multi-worker-3-9 ./worker

  #     # Push Images to docker hub
  #     - run: docker push oscardel13/oscarshub-client
  #     - run: docker push oscardel13/oscarshub-nginx
  #     - run: docker push oscardel13/oscarshub-server 
  #     # - run: docker push oscardel13/multi-worker-3-9 l

  deploy:
    # needs: build
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOSTNAME }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command: |
            echo "Hello from the EC2 instance!"
            docker-compose down
